<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
<?php
    echo $this->headTitle('Admin RiskMan');
    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0');
    echo $this->headLink(
            //change this to set an icon for the admin page
            array('rel' => 'icon', 'type' => 'image/png', 'href' => $this->basePath('/img/favicon.png'))
            )
        ->prependStylesheet('/examples/dashboard/assets/css/bootstrap.min.css')
        ->prependStylesheet('/examples/dashboard/assets/css/animate.min.css')
        ->prependStylesheet('/examples/dashboard/assets/css/light-bootstrap-dashboard.css')
        ->prependStylesheet('/app/css/main.css');
?>
        <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="/examples/dashboard/assets/css/pe-icon-7-stroke.css" rel="stylesheet" />
    </head>
    <body>
        <div class="wrapper">
            <div class="sidebar" data-color="green">
                <div class="sidebar-wrapper">
                    <div class="logo">
                        <a href="#" class="simple-text">
                            Admin RiskMan V1
                        </a>
                    </div>

                    <ul class="nav nav-stacked">
                        <li class="active">
                            <a href="/Admin">
                                <i class="pe-7s-graph"></i>
                                <p>Dashboard</p>
                            </a>
                        </li>
                        <li>
                            <a href="/Admin/Users">
                                <i class="pe-7s-user"></i>
                                <p>Users</p>
                            </a>
                        </li>
                        <li>
                            <a href="/Admin/Books">
                                <i class="pe-7s-note2"></i>
                                <p>Books</p>
                            </a>
                        </li>
                        <li>
                            <a href="/Admin/Reports">
                                <i class="pe-7s-news-paper"></i>
                                <p>Reports</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="main-panel">
                <nav class="navbar navbar-default navbar-fixed">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="#">Dashboard</a>
                        </div>
                        <div class="collapse navbar-collapse">
                            <ul class="nav navbar-nav navbar-left">
                                <li>
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <i class="fa fa-dashboard"></i>
                                    </a>
                                </li>
                                <li class="dropdown">
                                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            <i class="fa fa-globe"></i>
                                            <b class="caret"></b>
                                            <span class="notification">5</span>
                                      </a>
                                      <ul class="dropdown-menu">
                                        <li><a href="#">Notification 1</a></li>
                                        <li><a href="#">Notification 2</a></li>
                                        <li><a href="#">Notification 3</a></li>
                                        <li><a href="#">Notification 4</a></li>
                                        <li><a href="#">Another notification</a></li>
                                      </ul>
                                </li>
                                <li>
                                   <a href="">
                                        <i class="fa fa-search"></i>
                                    </a>
                                </li>
                            </ul>

                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                   <a href="">
                                       Account
                                    </a>
                                </li>
                                <li class="dropdown">
                                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            Dropdown
                                            <b class="caret"></b>
                                      </a>
                                      <ul class="dropdown-menu">
                                        <li><a href="#">Action</a></li>
                                        <li><a href="#">Another action</a></li>
                                        <li><a href="#">Something</a></li>
                                        <li><a href="#">Another action</a></li>
                                        <li><a href="#">Something</a></li>
                                        <li class="divider"></li>
                                        <li><a href="#">Separated link</a></li>
                                      </ul>
                                </li>
                                <li>
                                    <a href="/Auth/Logout">
                                        Log out
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <div class="content">
                    <div class="container-fluid">
                        <div class="container">
                            <?php echo $this->content; ?>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
        <footer>
            <hr>
            <div class="container center-block">
              <div class="row">
                <div class="col-sm-6"><p class="pull-left">
                    &copy; Copyright 2013 - <?php echo date('Y') ?>
                    by Rolf Bansbach
                </p></div>
              </div>
            </div>
        </footer>
        <script data-main="/app/js/require.config" src="/app/js/lib/requirejs/require.js"></script>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
